add plugin to publish detail report

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -25,8 +25,24 @@ jobs:
         run: mkdir -p test_results
       - name: Run tests with pytest
         run: pytest -vv --junitxml="test_results/result.xml"
-      - name: Publish Unit Test Results
-        uses: mikepenz/action-junit-report@v2
-        if: always()
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()      # run this step even if previous step failed
         with:
-          report_paths: 'test_results/*.xml'
+          name: test-results
+          path: 'test_results/result.xml'
+      - uses: dorny/test-reporter@v1
+        with:
+          artifact: test-results            # artifact name
+          name: Junit Tests Results         # Name of the check run which will be created
+          path: 'test_results/result.xml'   # Path to test results (inside artifact .zip)
+          reporter: java-junit              # Format of test results
+#      - name: Publish Unit Test Results
+#        uses: mikepenz/action-junit-report@v2
+#        if: always()
+#        with:
+#          report_paths: 'test_results/*.xml'
+#      - name: Publish Unit Test Results
+#        uses: EnricoMi/publish-unit-test-result-action@v1
+#        if: always()
+#        with:
+#          files: test_results/*.xml
